package static

import (
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/rs/zerolog/log"
)

// APIManager represents an API manager that manages the API definition,
// dependency graph, dataflow graph and other static information of the API.
type APIManager struct {
	// The OpenAPI definition of the API.
	APIDoc *openapi3.T

	// The map from the simple API method to the OpenAPI operation.
	APIMap map[SimpleAPIMethod]*openapi3.Operation

	// Internal APIs of the services in the system.
	InternalServiceAPIDoc *openapi3.T

	// The map from the service name to the map from the method to the OpenAPI operation.
	InternalServiceAPIMap map[string]map[SimpleAPIMethod]*openapi3.Operation

	// The dependency graph of the API.
	APIDependencyGraph *APIDependencyGraph

	// The Dataflow graph of the internal APIs.
	APIDataflowGraph *APIDataflowGraph

	// Reachability information of external APIs and internal service interfaces.
	// This map is initialized from API doc, and would not be updated in the process of fuzzing.
	// We will keep updating the dynamic (runtime) version in runtime package
	StaticReachabilityMap *ReachabilityMap
}

// NewAPIManager creates a new APIManager.
func NewAPIManager() *APIManager {
	return &APIManager{}
}

// InitFromDoc initializes the API manager from an OpenAPI document.
// The document is of interfaces of the whole system.
func (m *APIManager) InitFromSystemDoc(doc *openapi3.T) {
	m.APIDoc = doc
	m.APIMap = make(map[SimpleAPIMethod]*openapi3.Operation)
	for path, pathItem := range doc.Paths.Map() {
		for method, operation := range pathItem.Operations() {
			// By default, the type of the API is HTTP.
			simpleAPIMethod := SimpleAPIMethod{
				Method: method,
				Endpoint: path,
				Typ: SimpleAPIMethodTypeHTTP,
			}
			m.APIMap[simpleAPIMethod] = operation
		}
	}
}

// InitFromServiceDocs initializes the API manager from the OpenAPI document of the services.
func (m *APIManager) InitFromServiceDoc(doc *openapi3.T) {
	m.InternalServiceAPIDoc = doc
	m.InternalServiceAPIMap = make(map[string]map[SimpleAPIMethod]*openapi3.Operation)
	for _, pathItem := range doc.Paths.Map() {
		for _, operation := range pathItem.Operations() {
			// In OpenAPI generated by protoc-gen-openapi, operationID is in the format of `{Service}_{Method}`.
			// We can use this format to extract the service name and method name.
			operationID := operation.OperationID
			// Split the operationID by `_`.
			operationIDParts := strings.Split(operationID, "_")
			if len(operationIDParts) != 2 {
				log.Warn().Msgf("[APIManager.InitFromServiceDoc] Invalid operationID: %s", operationID)
				continue
			}
			serviceName := operationIDParts[0]
			methodName := operationIDParts[1]
			// TODO: we treat all internal interfaces as gRPC methods for now. @xunzhou24
			simpleMethod := SimpleAPIMethod{
				Endpoint: methodName,
				Method: methodName,
				Typ: SimpleAPIMethodTypeGRPC,
			}
			if _, exists := m.InternalServiceAPIMap[serviceName]; !exists {
				m.InternalServiceAPIMap[serviceName] = make(map[SimpleAPIMethod]*openapi3.Operation)
			}
			m.InternalServiceAPIMap[serviceName][simpleMethod] = operation
		}
	}

	// Generate the dataflow graph of the internal APIs.
	m.APIDataflowGraph = NewAPIDataflowGraph()
	m.APIDataflowGraph.ParseFromServiceDocument(m.InternalServiceAPIMap)
}

// GetOperationByMethod returns the OpenAPI operation of the given API method.
func (m *APIManager) GetOperationByMethod(method SimpleAPIMethod) (*openapi3.Operation, bool) {
	if operation, ok := m.APIMap[method]; ok {
		return operation, true
	}
	return nil, false
}

// GetRandomAPIMethod returns a random API method from the API manager.
func (m *APIManager) GetRandomAPIMethod() SimpleAPIMethod {
	// Golang map iteration order is random.
	// See [official doc](https://go.dev/blog/maps#iteration-order).
	for method := range m.APIMap {
		return method
	}
	log.Warn().Msg("[APIManager.GetRandomAPIMethod] APIMap is empty, return empty method")
	return SimpleAPIMethod{}
}

// GetConsumerAPIMethodsByProducers returns the consumer API methods of the given producer API methods.
// You should set the `APIDependencyGraph` field of the API manager before calling this function.
func (m *APIManager) GetConsumerAPIMethodsByProducers(producers []SimpleAPIMethod) []SimpleAPIMethod {
	var res []SimpleAPIMethod
	for _, producer := range producers {
		if consumers, ok := m.APIDependencyGraph.Graph[producer]; ok {
			res = append(res, consumers...)
		}
	}
	return res
}
