package config

import (
	"flag"
	// "fmt"
	// "os"

	"github.com/bytedance/sonic"
	"github.com/rs/zerolog/log"
)

func ParseCmdArgs() {
	flag.StringVar(&GlobalConfig.OpenAPISpecPath, "openapi-spec", "", "Path to the OpenAPI spec file")
	flag.StringVar(&GlobalConfig.DependencyFilePath, "dependency-file", "", "Path to the dependency file generated by other tools or manually")
	flag.StringVar(&GlobalConfig.DependencyFileType, "dependency-file-type", "Restler", "Type of the dependency file. Currently only support 'Restler'")
	flag.Parse()

	jsonStr, _ := sonic.Marshal(GlobalConfig)
	log.Info().Msgf("Parsed command line arguments: %s", jsonStr)

}
	
